// Vendor locked browser builds so the generated page remains self-contained.

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));

// The packages' export maps do not expose these browser builds.
const ASSETS = [
  {
    package: "cytoscape",
    file: "dist/cytoscape.min.js",
    constant: "CYTOSCAPE",
    notice: "MIT licensed, (c) The Cytoscape Consortium",
  },
  {
    package: "marked",
    file: "lib/marked.umd.js",
    constant: "MARKED",
    notice: "MIT licensed, (c) MarkedJS and Christopher Jeffrey",
  },
  {
    package: "dompurify",
    file: "dist/purify.min.js",
    constant: "DOMPURIFY",
    notice: "Apache-2.0 or MPL-2.0, (c) Cure53 and other contributors",
  },
];

for (const asset of ASSETS) {
  const home = join(root, "node_modules", asset.package);
  const manifest = JSON.parse(await readFile(join(home, "package.json"), "utf8"));
  const source = await readFile(join(home, asset.file), "utf8");

  // A closing tag would end the generated inline script early.
  if (/<\/script/i.test(source)) {
    throw new Error(`${asset.package} contains a closing script tag and cannot be inlined as is`);
  }

  const module = `// Generated by scripts/vendor.mjs. Do not edit; run \`pnpm vendor\` instead.
//
// ${asset.package} ${manifest.version}, ${asset.notice}. The full license travels in the source
// below, which begins with its own banner.

export const ${asset.constant}_VERSION = ${JSON.stringify(manifest.version)};

export const ${asset.constant}_SOURCE = ${JSON.stringify(source)};
`;

  const output = join(root, "src", "vendor", `${asset.package}.ts`);
  if ((await readFile(output, "utf8").catch(() => null)) === module) {
    continue;
  }

  await mkdir(dirname(output), { recursive: true });
  await writeFile(output, module, "utf8");
  console.log(
    `vendored ${asset.package} ${manifest.version} (${source.length} bytes) into src/vendor/${asset.package}.ts`,
  );
}
