import assert from "node:assert/strict";
import test from "node:test";

import type {
  AnalyzedDocument,
  AnalyzedLink,
  BundleAnalysis,
  BundleGraphEdge,
  BundleGraphNode,
} from "okf-contracts";
import { toVisualizationGraph } from "okf-viz";
import {
  DARK_THEME,
  graphStylesheet,
  layoutOptions,
  LIGHT_THEME,
  nodeClasses,
} from "okf-viz/browser";

import { generateVisualization, GeneratorError } from "../src/index.js";
import { PAGE_SCRIPT } from "../src/page/script.js";
import { PAGE_STYLE } from "../src/page/style.js";

const POSITION = { line: 1, column: 1, offset: 0 } as const;
const RANGE = { start: POSITION, end: POSITION } as const;

function link(href: string, resolvedPath: string): AnalyzedLink {
  return {
    href,
    text: resolvedPath,
    kind: "internal",
    resolvedPath,
    fragment: null,
    exists: true,
    range: RANGE,
  };
}

function document(
  path: string,
  title: string,
  type: string,
  body: string,
  links: readonly AnalyzedLink[] = [],
): AnalyzedDocument {
  return {
    path,
    id: path === "index.md" ? null : path.slice(0, -3),
    kind: path === "index.md" ? "index" : "concept",
    revision: null,
    content: body,
    body,
    bodyStartLine: 1,
    frontmatter: null,
    metadata: {},
    links,
    derived: {
      title,
      type,
      description: `${title} description`,
      status: "stable",
      trustTier: "unverified",
      stale: false,
      staleAfter: null,
      tags: [],
      sources:
        path === "concepts/one.md"
          ? [
              {
                id: null,
                resource: "https://example.com/one",
                title: "Example",
                author: null,
                usageCount: null,
                lastModified: null,
                resolvedPath: null,
                exists: null,
              },
            ]
          : [],
    },
  };
}

function node(path: string, title: string, type: string): BundleGraphNode {
  return {
    id: path,
    path,
    title,
    type,
    description: `${title} description`,
    status: "stable",
    trustTier: "unverified",
    stale: false,
    tags: [],
  };
}

function edge(source: string, target: string, id = "edge"): BundleGraphEdge {
  return { id, source, target, relation: "link" };
}

function analysis(
  documents: readonly AnalyzedDocument[],
  nodes: readonly BundleGraphNode[],
  edges: readonly BundleGraphEdge[],
): BundleAnalysis {
  return {
    schema: "okf.inspect.v1",
    okfVersion: "0.2",
    documents,
    graph: { nodes, edges },
    diagnostics: { core: [], guidance: [], profile: [] },
    summary: {
      documents: documents.length,
      concepts: documents.filter((entry) => entry.kind === "concept").length,
      indexes: documents.filter((entry) => entry.kind === "index").length,
      logs: 0,
      errors: 0,
      warnings: 0,
    },
  };
}

const INDEX = document(
  "index.md",
  "Bundle index",
  "Index",
  "# Bundle index\n\nRead [one](concepts/one.md).\n",
  [link("concepts/one.md", "concepts/one.md")],
);
const ONE = document(
  "concepts/one.md",
  "One",
  "Concept",
  "# One\n\nBack to [index](../index.md).\n",
  [link("../index.md", "index.md")],
);
const BUNDLE = analysis(
  [INDEX, ONE],
  [node("index.md", "Bundle index", "Index"), node("concepts/one.md", "One", "Concept")],
  [edge("index.md", "concepts/one.md", "a"), edge("concepts/one.md", "index.md", "b")],
);

test("preserves canonical graph relations and distinguishes source edges", () => {
  const sourceEdge: BundleGraphEdge = {
    id: "source",
    source: "index.md",
    target: "concepts/one.md",
    relation: "source",
  };
  const graph = toVisualizationGraph({
    ...BUNDLE,
    graph: { ...BUNDLE.graph, edges: [sourceEdge] },
  });
  assert.deepEqual(graph.edges, [
    {
      id: "e0",
      source: "index.md",
      target: "concepts/one.md",
      relation: "source",
      attested: false,
    },
  ]);
  assert.match(
    generateVisualization({
      bundle: "handbook",
      analysis: { ...BUNDLE, graph: { ...BUNDLE.graph, edges: [sourceEdge] } },
    }),
    /edge\[relation = \\"source\\"\]/,
  );
});

test("same analysis generates byte-identical output", () => {
  const first = generateVisualization({ bundle: "handbook", analysis: BUNDLE });
  const second = generateVisualization({ bundle: "handbook", analysis: BUNDLE });
  assert.equal(first, second);
  assert.equal(/\b20\d\d-\d\d-\d\dT\d\d:/.test(first), false);
});

test("input collection order does not affect generated bytes", () => {
  const shuffled = analysis(
    [ONE, INDEX],
    [...BUNDLE.graph.nodes].reverse(),
    [...BUNDLE.graph.edges].reverse(),
  );
  assert.equal(
    generateVisualization({ bundle: "handbook", analysis: BUNDLE }),
    generateVisualization({ bundle: "handbook", analysis: shuffled }),
  );
});

test("page is self-contained and its CSP names no origin", () => {
  const html = generateVisualization({ bundle: "handbook", analysis: BUNDLE });
  assert.equal(/<script[^>]+\bsrc=/i.test(html), false);
  assert.equal(/<link[^>]+\bhref=/i.test(html), false);
  assert.match(html, /default-src 'none'/);
  assert.match(html, /connect-src 'none'/);
  assert.match(html, /base-uri 'none'/);
  assert.match(html, /cytoscape 3\./i);
  assert.match(html, /marked 18\./i);
  assert.match(html, /DOMPurify 3\./i);
});

test("stored content cannot end the JSON script element", () => {
  const hostileDocument = document(
    "index.md",
    "</script><script>alert(1)</script>",
    "Index",
    "<img src=x onerror=alert(2)>\n</script><script>alert(3)</script>",
  );
  const hostile = analysis(
    [hostileDocument],
    [node("index.md", hostileDocument.derived.title, "Index")],
    [],
  );
  const html = generateVisualization({ bundle: "hostile", analysis: hostile });

  assert.equal(html.match(/<\/script>/g)?.length, 5);
  const match = /<script id="okf-graph" type="application\/json">([\s\S]*?)<\/script>/.exec(html);
  assert.ok(match);
  const payload = match[1] ?? "";
  assert.equal(payload.includes("<"), false);
  assert.match(payload, /\\u003c\/script\\u003e\\u003cscript\\u003ealert\(1\)/);
  assert.equal(JSON.parse(payload).graph.nodes[0].title, hostileDocument.derived.title);
});

test("browser behavior renders with Marked then sanitizes with DOMPurify", () => {
  const marked = PAGE_SCRIPT.indexOf("marked.parse");
  const sanitized = PAGE_SCRIPT.indexOf("DOMPurify.sanitize");
  const assignment = PAGE_SCRIPT.indexOf("container.innerHTML = DOMPurify.sanitize");
  assert.ok(marked >= 0);
  assert.ok(sanitized > marked);
  assert.equal(assignment, sanitized - "container.innerHTML = ".length);
  assert.match(PAGE_SCRIPT, /FORBID_TAGS: \["img", "form", "input", "textarea", "select", "style"\]/);
  assert.match(PAGE_SCRIPT, /FORBID_ATTR: \["style"\]/);
  assert.equal((PAGE_SCRIPT.match(/\.innerHTML\s*=/g) ?? []).length, 1);
});

test("unknown analysis schema is rejected", () => {
  const unsupported = { ...BUNDLE, schema: "okf.inspect.v2" } as unknown as BundleAnalysis;
  assert.throws(
    () => generateVisualization({ bundle: "handbook", analysis: unsupported }),
    (error: unknown) => error instanceof GeneratorError && /unsupported analysis schema/.test(error.message),
  );
});

/** A node with explicit trust signals, for the projection tests below. */
function signalNode(
  path: string,
  overrides: Partial<BundleGraphNode>,
): BundleGraphNode {
  return { ...node(path, path, "Concept"), ...overrides };
}

function signalDocument(path: string, staleAfter: string | null): AnalyzedDocument {
  const base = document(path, path, "Concept", `# ${path}\n`);
  return { ...base, derived: { ...base.derived, staleAfter } };
}

test("omitting evaluatedAt leaves the page reproducible from the bundle alone", () => {
  const documents = [signalDocument("concepts/a.md", null)];
  const html = generateVisualization({
    bundle: "b",
    analysis: analysis(documents, [signalNode("concepts/a.md", {})], []),
  });
  // The page script always contains the label literal; what matters is the payload it reads.
  assert.match(html, /"evaluatedAt":null/);
  assert.match(html, /<span class="muted" id="evaluated"><\/span>/);
});

test("evaluatedAt must be a real calendar date", () => {
  const documents = [signalDocument("concepts/a.md", null)];
  const input = analysis(documents, [signalNode("concepts/a.md", {})], []);
  for (const bad of ["2026-8-31", "2026-02-30", "2026-08-31T00:00:00Z", "nonsense"]) {
    assert.throws(
      () => generateVisualization({ bundle: "b", analysis: input, evaluatedAt: bad }),
      GeneratorError,
      bad,
    );
  }
});

test("dating the page without dating the analysis is refused", () => {
  // stale_after present but every verdict null means the caller forgot analyzeBundle({today}).
  const documents = [signalDocument("concepts/a.md", "2026-01-01")];
  const nodes = [signalNode("concepts/a.md", { stale: null })];
  assert.throws(
    () => generateVisualization({
      bundle: "b",
      analysis: analysis(documents, nodes, []),
      evaluatedAt: "2026-08-31",
    }),
    /not evaluated against a date/,
  );
});

test("the same triple always produces the same bytes", () => {
  const documents = [signalDocument("concepts/a.md", "2026-01-01")];
  const nodes = [signalNode("concepts/a.md", { stale: true })];
  const input = { bundle: "b", analysis: analysis(documents, nodes, []), evaluatedAt: "2026-08-31" };
  assert.equal(generateVisualization(input), generateVisualization(input));
  // The date is an input, so changing it is expected to change the bytes.
  assert.notEqual(
    generateVisualization(input),
    generateVisualization({ ...input, evaluatedAt: "2026-09-01" }),
  );
});

test("the reader is laid out beside the graph and can still scroll", () => {
  const documents = [signalDocument("concepts/a.md", null)];
  const html = generateVisualization({
    bundle: "b",
    analysis: analysis(documents, [signalNode("concepts/a.md", {})], []),
  });
  assert.ok(html.indexOf('id="graph"') < html.indexOf('id="split"'));
  assert.ok(html.indexOf('id="split"') < html.indexOf('id="detail"'));
  assert.match(html, /main \{ display: flex; flex-direction: row;/);
  // The graph draws type, authorship and trust; it still carries no legend row, because the
  // reader's metadata table is where a signal gets named in words rather than in a key.
  assert.ok(!html.includes('id="legend"'), "no legend row");
  // The stylesheet is okf-viz's, embedded as data. Its rule order is that package's
  // invariant and is tested there; here the question is only whether it arrived.
  assert.match(html, /"selector":"node\.author-human"/);
  assert.match(html, /"selector":"node\.unchecked"/);
  // Cytoscape resolves conflicts by array order and the last rule wins. Stale must therefore
  // follow both fading rules, and every new rule must precede selection and filtering.
  assert.ok(html.indexOf('"node.unchecked"') < html.indexOf('"node.stale"'), "stale beats dimming");
  assert.ok(html.indexOf('"node.deprecated"') < html.indexOf('"node.stale"'), "stale beats dimming");
  assert.ok(html.indexOf('"node.stale"') < html.indexOf('"node:selected"'), "selection still draws");
  assert.ok(html.indexOf('"node:selected"') < html.indexOf('".dim"'), "filtering still draws");
  assert.match(html, /main\[data-orientation="rows"\] \{ flex-direction: column; \}/);
  assert.match(html, /#detail \{[^}]*min-height: 0;[^}]*overflow-y: auto;/s);
});

test("browser storage is guarded and names no origin", () => {
  assert.match(PAGE_SCRIPT, /okf\.viz\.prefs\.v1/);
  assert.match(PAGE_SCRIPT, /try \{[\s\S]*localStorage[\s\S]*catch/);
  assert.ok(!/iteramind|https?:\/\//i.test(PAGE_SCRIPT));
});

test("embedded page sources carry no backtick, which would end their template literal", () => {
  // PAGE_SCRIPT and PAGE_STYLE are String.raw template literals. A backtick anywhere inside
  // them - including in a comment - terminates the literal and produces a syntax error in the
  // built module. That failure surfaces only when the package is imported, so pin it here.
  assert.ok(!PAGE_SCRIPT.includes("`"), "PAGE_SCRIPT must contain no backtick");
  assert.ok(!PAGE_STYLE.includes("`"), "PAGE_STYLE must contain no backtick");
});

test("the built page module imports cleanly", async () => {
  // A regression that only appears on import would otherwise pass every other assertion here.
  const module = await import("../src/page/script.js");
  assert.equal(typeof module.PAGE_SCRIPT, "string");
});

/** A document whose raw frontmatter carries the provenance families. */
function provenanceDocument(
  path: string,
  metadata: Record<string, unknown>,
  sources: AnalyzedDocument["derived"]["sources"] = [],
): AnalyzedDocument {
  const base = document(path, path, String(metadata["type"] ?? "Concept"), `# ${path}\n`);
  return {
    ...base,
    metadata: metadata as AnalyzedDocument["metadata"],
    derived: { ...base.derived, staleAfter: null, sources },
  };
}

test("the panel offers a verification row and a computation section", () => {
  const documents = [provenanceDocument("concepts/a.md", { type: "Concept" })];
  const html = generateVisualization({
    bundle: "b",
    analysis: analysis(documents, [signalNode("concepts/a.md", {})], []),
  });
  assert.match(html, /id="detail-verified"/);
  assert.match(html, /id="detail-generated"/);
  assert.match(html, /id="detail-computation"/);
  // The collapsed one-word row it replaced is gone.
  assert.ok(!html.includes('id="detail-trust"'));
});

test("each type gets its own shape, and an unmapped type falls back to an ellipse", () => {
  const expected: readonly (readonly [string, string])[] = [
    ["Attested Computation", "star"],
    ["Decision", "diamond"],
    ["Policy", "hexagon"],
    ["Runbook", "round-rectangle"],
    ["Guide", "rhomboid"],
    ["Project", "tag"],
    // The one-word spelling folds onto the same key, rather than drifting to a second shape.
    ["ProjectBrief", "tag"],
    ["Concept", "ellipse"],
    ["Organization", "pentagon"],
    ["Service", "barrel"],
    ["Metric", "triangle"],
    ["Index", "octagon"],
    // Nothing in the map: the neutral ellipse, never another type's shape.
    ["Ephemeris", "ellipse"],
  ];

  for (const [type, shape] of expected) {
    const graph = toVisualizationGraph(analysis(
      [provenanceDocument("concepts/a.md", { type })],
      [signalNode("concepts/a.md", { type })],
      [],
    ));
    assert.equal(graph.nodes[0]?.shape, shape, type);
  }

  // The shape is decided in the projection, so the browser reads it rather than deciding it.
  const html = generateVisualization({
    bundle: "b",
    analysis: analysis(
      [provenanceDocument("concepts/c.md", { type: "Attested Computation" })],
      [signalNode("concepts/c.md", { type: "Attested Computation" })],
      [],
    ),
  });
  assert.match(html, /"shape":"star"/);
  assert.match(html, /"shape":"data\(shape\)"/);
});

test("a link to an Attested Computation is drawn as its own kind of edge", () => {
  const documents = [
    provenanceDocument("concepts/a.md", { type: "Concept" }),
    provenanceDocument("concepts/c.md", { type: "Attested Computation" }),
  ];
  const nodes = [
    signalNode("concepts/a.md", {}),
    signalNode("concepts/c.md", { type: "Attested Computation" }),
  ];
  const edges = [
    edge("concepts/a.md", "concepts/c.md", "leans-on"),
    edge("concepts/c.md", "concepts/a.md", "cites-back"),
  ];
  const graph = toVisualizationGraph(analysis(documents, nodes, edges));
  const intoComputation = graph.edges.find((entry) => entry.target === "concepts/c.md");
  const outOfComputation = graph.edges.find((entry) => entry.target === "concepts/a.md");

  assert.equal(intoComputation?.attested, true);
  // Direction is the whole point: leaving the computation is an ordinary link.
  assert.equal(outOfComputation?.attested, false);
  // The flag sits beside the relation rather than replacing it, so a cited computation is
  // still recognisable as a citation.
  assert.equal(intoComputation?.relation, "link");

  const html = generateVisualization({ bundle: "b", analysis: analysis(documents, nodes, edges) });
  assert.match(html, /"selector":"edge\.attested"/);
  assert.ok(html.indexOf('"edge.attested"') < html.indexOf('"edge:selected"'));
});

test("hovering a node describes it without taking over the selection", () => {
  assert.match(PAGE_SCRIPT, /cy\.on\("mouseover", "node"/);
  assert.match(PAGE_SCRIPT, /function showHover\(node, rendered\)/);
  // The card is assembled, never parsed: a title that looks like markup stays text.
  assert.match(PAGE_SCRIPT, /hoverCard\.replaceChildren\(\)/);
  assert.ok(!PAGE_SCRIPT.includes("hoverCard.innerHTML"));
  assert.equal((PAGE_SCRIPT.match(/\.innerHTML\s*=/g) ?? []).length, 1);
  // showHover must not select: hovering answers a question, it does not replace the answer
  // the reader is already looking at.
  const hover = PAGE_SCRIPT.slice(PAGE_SCRIPT.indexOf("function showHover"));
  assert.ok(!hover.slice(0, hover.indexOf("cy.on(\"mouseout\"")).includes(".select()"));
});

test("the dated strip ships hidden, above the table it summarises", () => {
  const documents = [provenanceDocument("concepts/a.md", { type: "Concept" })];
  const html = generateVisualization({
    bundle: "b",
    analysis: analysis(documents, [signalNode("concepts/a.md", {})], []),
  });
  assert.match(html, /<section id="detail-timeline"[^>]*\bhidden>/);
  assert.match(html, /id="timeline-marks"/);
  assert.match(html, /id="timeline-overrun"/);
  // The strip belongs with the page identity, above the metadata it condenses.
  assert.ok(html.indexOf('id="detail-path"') < html.indexOf('id="detail-timeline"'));
  assert.ok(html.indexOf('id="detail-timeline"') < html.indexOf("<dl>"));
});

test("a page with no dates leaves the strip with nothing to draw", () => {
  const documents = [provenanceDocument("concepts/a.md", { type: "Concept" })];
  const html = generateVisualization({
    bundle: "b",
    analysis: analysis(documents, [signalNode("concepts/a.md", {})], []),
  });
  // Nothing is dated, so the script finds no event and the markup's hidden attribute stands.
  assert.match(html, /"generated":null/);
  assert.match(html, /"verified":\[\]/);
  assert.match(html, /"staleAfter":null/);
  assert.match(PAGE_SCRIPT, /timelineSection\.hidden = !events\.length;/);
  // An explicit display rule on the section would silently defeat that attribute.
  assert.match(PAGE_STYLE, /#detail-timeline \{ margin: 0 0 18px; \}/);
  assert.match(PAGE_STYLE, /\[hidden\] \{ display: none !important; \}/);
});

test("an expired page draws the overrun between its expiry and the evaluation date", () => {
  const documents = [signalDocument("concepts/a.md", "2026-01-01")];
  const nodes = [signalNode("concepts/a.md", { stale: true })];
  const html = generateVisualization({
    bundle: "b",
    analysis: analysis(documents, nodes, []),
    evaluatedAt: "2026-08-31",
  });
  assert.match(html, /"staleAfter":"2026-01-01"/);
  assert.match(html, /"evaluatedAt":"2026-08-31"/);
  // Geometry: the overrun spans expiry to today, and says how far past in words.
  assert.match(PAGE_SCRIPT, /timelineOverrun\.style\.left = left \+ "%";/);
  assert.match(PAGE_SCRIPT, /timelineOverrun\.hidden = false;/);
  assert.match(PAGE_SCRIPT, /past its stale-after date/);
  // Hatched, so the overrun still reads where the accent colour does not.
  assert.match(PAGE_STYLE, /\.timeline-overrun \{/);
  assert.match(PAGE_STYLE, /repeating-linear-gradient/);
});

test("source usage is drawn as a bar scaled to the busiest source on the page", () => {
  const documents = [provenanceDocument("concepts/a.md", { type: "Concept", usage_window: { from: "2026-06-01", to: "2026-06-30" } }, [
    {
      id: "policy",
      resource: "https://example.com/policy",
      title: "Revenue policy",
      author: "human:jordi",
      usageCount: 5000,
      lastModified: "2026-06-15",
      resolvedPath: null,
      exists: null,
    },
    {
      id: "warehouse",
      resource: "https://example.com/warehouse",
      title: "Warehouse schema",
      author: null,
      usageCount: 1240,
      lastModified: null,
      resolvedPath: null,
      exists: null,
    },
  ])];
  const html = generateVisualization({
    bundle: "b",
    analysis: analysis(documents, [signalNode("concepts/a.md", {})], []),
  });
  assert.match(html, /"usageCount":5000/);
  assert.match(html, /"usageWindow":\{"from":"2026-06-01","to":"2026-06-30"\}/);
  // Proportional to the largest count on the page, never to a bundle-wide maximum.
  assert.match(PAGE_SCRIPT, /fill\.style\.width = \(\(source\.usageCount \/ largest\) \* 100\) \+ "%";/);
  assert.match(PAGE_SCRIPT, /source\.usageCount !== null && source\.usageCount > largest/);
  // The window is a property of the measurement, so it is stated once for the whole list.
  assert.match(PAGE_SCRIPT, /sourcesEl\.appendChild\(caption\);/);
  assert.match(PAGE_STYLE, /\.usage-bar \{/);
  assert.match(PAGE_STYLE, /\.usage-fill \{/);
});

/** The embedded payload, which is where the graph's encoding now travels. */
function payloadOf(html: string): {
  encoding: {
    classes: Record<string, string[]>;
    layout: Record<string, unknown>;
    style: { dark: unknown[]; light: unknown[] };
  };
} {
  const found = /id="okf-graph" type="application\/json">([\s\S]*?)<\/script>/.exec(html);
  assert.ok(found !== null, "the page carries no payload");
  return JSON.parse(found[1] ?? "{}");
}

test("the page carries the library's encoding rather than a copy of it", () => {
  /*
   * The point of the split. The page used to build the Cytoscape stylesheet and the node
   * classes itself, so there were two implementations of what a node looks like and nothing
   * keeping them in step. Equality here is what makes okf-viz the only one: a rule the library
   * changes reaches the page without anybody editing this package.
   */
  const encoding = payloadOf(generateVisualization({ bundle: "handbook", analysis: BUNDLE }))
    .encoding;

  assert.deepEqual(encoding.style.dark, graphStylesheet(DARK_THEME));
  assert.deepEqual(encoding.style.light, graphStylesheet(LIGHT_THEME));
  assert.deepEqual(encoding.layout, layoutOptions("cose"));

  // Both themes travel because the authorship ring is chosen at view time: a near-black ring
  // is invisible on a dark background, and that ring is a signal that must always read.
  assert.notDeepEqual(encoding.style.dark, encoding.style.light);

  const graph = toVisualizationGraph(BUNDLE);
  for (const node of graph.nodes) {
    assert.deepEqual(encoding.classes[node.id], nodeClasses(node), `classes for ${node.id}`);
  }
});

test("this package declares no graph encoding of its own", async () => {
  // A rule written here again would be a second implementation, however it was spelled.
  const { readFile } = await import("node:fs/promises");
  const { join } = await import("node:path");
  const script = await readFile(join(process.cwd(), "src", "page", "script.ts"), "utf8");
  assert.doesNotMatch(script, /selector:/);
  assert.doesNotMatch(script, /"border-style"|"background-color"|target-arrow-shape/);
  assert.match(script, /payload\.encoding\.style/);
});
